hubmapconsortium/ccf-validation-tools

src/Makefile
src/ccf_tools.py
src/class_template_Heart.tsv
src/ind_template_Heart.tsv
src/template_runner.py
src/uberongraph_tools.py

Draft asctb parser

---

src/download_resource.py

Update sheet's version in the mapping

---

reports/report_relationship_20211029.tsv
reports/report_relationship_20211101.tsv
reports/report_terms_20211029.tsv
reports/report_terms_20211101.tsv
src/Makefile
src/ccf_tools.py
src/download_resource.py
src/template_generation_tools.py

Make reports more granular

---

src/uberongraph_tools.py

Update ubergraph endpoint

---

src/download_resource.py

Change function to load JSON

---

.github/workflows/release.yaml
NOTES.md
requirements.txt
src/Makefile
src/download_resource.py
src/release_notes_generation.py
src/uberongraph_tools.py

Create release notes based on the asct tables' and ontologies' version

---

src/Makefile
src/template_generation_tools.py

Split requests in chunks

---

src/download_resource.py

Update date and version

---

src/ccf_tools.py
src/template_runner.py

Create new uberon term report

---

src/download_resource.py

Update asct+b api address

---

src/template_generation_tools.py

Fix term report summary generation

---

src/ccf_tools.py

Remove duplicate errors on Blank ontology ID report

---

docs/Eye/relationship_validation.md
mkdocs.yml

Add a page with suggestions for experts how to improve the validations.

Add a suggestion page to improve the eye validation.

---

docs/Lung/change_suggestions.md
mkdocs.yml

Currently only AS-AS suggestions. Probably deploy as it is, and Create the rest in a new PR.

Create lung suggestion page

---

docs/Eye/relationship_validation.md
docs/Lung/change_suggestions.md

Relationships have been update for the latest version of the eye ASCT+B table (08/05/2023).

Update eye relationships

---

docs/Lung/change_suggestions.md

Update after call with lung expert

Update after call with lung expert

---

src/template_generation_tools.py

Validate `as has_part as`

---

src/helper.owl
src/template_generation_tools.py
src/uberongraph_tools.py

Add `continuous_with` to validation relationships

---

src/hra_wrapper.py
src/template_runner.py

create component linking 3d images with uberon terms

---

src/config_asct.json

Update tables version

---

src/Makefile

Fix old logs in current validation reports

---

src/Makefile

Fix reports not being updated

---

src/readme_reports_generation.py

Fix CT-AS report in the validation page

---

src/ccf_tools.py
src/readme_reports_generation.py
style/ubergraph-style.json

This is needed for adding the new tables Anatomical Systems and Mammary Gland.

Fix when there's one valid AS and no valid CT

---

docs/Pancreas/change_suggestions.md
mkdocs.yml

Create a feedback page for pancreas relations

Create a feedback page for pancreas relations

---

src/ccf_tools.py
src/dashboard_generation.py
src/readme_reports_generation.py
src/template_generation_tools.py

Blank ontology ID without CL parent Report

---

src/uberongraph_tools.py

This is the reason the last release failed.

add missing PCL prefix on queries

---

docs/Pancreas/change_suggestions.md

Update pancreas relations

---

docs/Pancreas/change_suggestions.md

Update suggestions to fix pancreas relations

Update suggestions to fix pancreas relations

---

docs/Eye/relationship_validation.md
docs/Pancreas/change_suggestions.md

Old arrows were -->, try &rarr; to create proper arrows in markdown

Changing arrows to a proper one

---

docs/Lung/change_suggestions.md

Update lung table

---

src/ccf_tools.py
src/dashboard_generation.py

[Dashboard] Split # invalid terms in temp and terms from other ont for AS and CT

---

src/config_asct.json

- Add sheetId and gid for Blood Vasculature v1.6
- Fix Main Bronchus sheetId

Update ASCT+B config

---

.github/workflows/build.yaml
src/template_generation_tools.py
src/uberongraph_tools.py

Also change the tables in the test qc

Fix typo in variable

---

src/template_generation_tools.py

Report diff label for each term in all rows to ensure same term uses same label

---

src/dashboard_generation.py
src/template_generation_tools.py

Add number of unique cases "no CL parent for ASCT-TEMP" to dashboard

---

mkdocs.yml
src/readme_reports_generation.py

Fix spelling for blood vasculature in mkdocs

Fix spelling for blood vasculature in mkdocs
